name: EMNLP2023
display_name: EMNLP 2023
tagline: The 2023 Conference on Empirical Methods in Natural Language Processing
date: December 6 &ndash; 10 <br> 2023
proceedings_title: The 2023 Conference on Empirical Methods in Natural Language Processing
citation_date: December 2023
analytics: G-9X8H03BYC2
site_url: https://virtual.2023.emnlp.org
logo:
  image: static/images/emnlp2023/emnlp-2023-logo.png
  height: 45px
site_title: EMNLP 2023
page_title:
  prefix: 'EMNLP2023'
  separator: ': '
background_image: static/images/emnlp2023/singapore_1.jpg
organization: Association for Computational Linguistics
social_tag: '#emnlp2023'

# Path to the folder of paper images.
paper_images_path: https://emnlp2020-public.s3.amazonaws.com/paper_images

default_presentation_id: 38931484

# Remove or change to your chat server.
enable_chat: true
chat_server: acl.rocket.chat
channels_stats_server: https://emnlp2020-channels-stats.azure-api.net

gather_town: https://www.virtualchair.net/events/emnlp2023
connected_papers_conference_name: EMNLP2023

calendar:
  start: '2023-12-06'
  end: '2023-12-10'

navigation_bar:
  order:
    - Home
  links:
    Home: index.html
    Schedule: schedule.html
    Papers: papers.html
    Organizers: https://2023.emnlp.org/organization/,
 
